config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  resources :folders, only: :create
  resources :notes, only: :create

  get '*path', to: 'folders#show'


  root to: 'folders#show'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/folder.rb
class Folder < ApplicationRecord
  has_many :sub_folders, class_name: 'Folder', foreign_key: 'parent_id', dependent: :destroy
  has_many :notes
  belongs_to :parent, class_name: 'Folder'

  scope :root, -> { find_by(parent_id: nil) }

  validates :name, uniqueness: { scope: 'parent_id' }

  def root?
    !parent_id?
  end

  def permalink
    return "/" if root?

    "#{parent.permalink}#{name}/"
  end
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :folder

  validates :name, uniqueness: { scope: 'folder_id' }

  def permalink
    "#{folder.permalink}#{name}"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/folders_controller.rb
# frozen_string_literal: true

class FoldersController < ApplicationController
  def show
    @folder_service = Folders::Show.new(folder_params.fetch(:path, ""))
  end

  def create
    folder = Folder.create(create_params)

    redirect_to folder.parent.permalink
  end

  private

    def create_params
      params.require(:folder).permit(:parent_id, :name)
    end

    def folder_params
      params.permit(:path)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    note = Note.create(create_params)

    redirect_to note.permalink
  end

  private

    def create_params
      params.require(:note).permit(:folder_id, :name, :body)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @notes = if search_params.present?
               Folders::SubdirectoriesFinder.new(search_params).find
             else
               Note.all
             end
  end

  def search_params
    params.permit(:id, :name).to_hash.symbolize_keys
  end
end

app/views/folders/_entries.html.erb
<div class="cell small-9 main-column">
  <div class="card">
    <div class="card-divider">
      Folders and Files
    </div>
    <div class="card-section">
      <ul class="list-group">
        <% unless folder_service.folder.root? %>
          <li class="list-group-item">
            <i class="fa fa-folder"></i>
            <%= link_to '..', folder_service.folder.parent.permalink %>
          </li>
        <% end %>


        <% folder_service.folders.each do |folder| %>
          <li class="list-group-item">
            <i class="fa fa-folder"></i>
            <%= link_to folder.name, folder.permalink %>
          </li>
        <% end %>

        <% folder_service.notes.each do |note| %>
          <li class="list-group-item">
            <i class="fa fa-sticky-note"></i>
            <%= link_to note.name, note.permalink %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/folders/_folder_form.html.erb
<div class="card">
  <div class="card-divider">
    Create new folder
  </div>
  <%= form_for Folder.new(parent: parent_folder) do |f| %>
    <div class="grid-container">
      <div class="grid-x grid-padding-x">
        <div class="medium-12 cell">
          <%= f.label :name %>
          <%= f.text_field :name %>
          <%= f.hidden_field :parent_id %>

          <%= f.submit :save, class: 'button' %>
        </div>
      </div>
    </div>

  <% end %>
</div>

app/views/folders/_note.html.erb
<div class="cell small-9 main-column">
  <div class="card">
    <div class="card-divider">
      <p><%= note.body %></p>
    </div>
    <div class="card-section">
      <h5><%= note.name %></h5>
    </div>
  </div>
</div>

app/views/folders/_note_form.html.erb
<div class="cell small-9 main-column">
  <div class="card">
    <div class="card-divider">
      New Note
    </div>
    <div class="card-section">
      <%= form_for Note.new(folder: parent_folder) do |f| %>
        <div class="grid-container">
          <div class="grid-x grid-padding-x">
            <div class="medium-12 cell">
              <%= f.label :name %>
              <%= f.text_field :name %>

              <%= f.label :body %>
              <%= f.text_area :body %>

              <%= f.hidden_field :folder_id %>

              <%= f.submit :save, class: 'button' %>
            </div>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/folders/_search.html.erb
<div class="cell small-9 main-column">
  <div class="card">
    <div class="card-divider">
      Search note
    </div>
    <div class="card-section">
      <%= form_tag search_index_path, method: "get"  do |f| %>

        <%= hidden_field_tag :id, folder&.id || Folder.root.id  %>

        <%= label_tag :search %>
        <%= text_area_tag :name %>

        <%= submit_tag :search, class: 'button' %>

      <% end %>
    </div>
  </div>
</div>

app/views/folders/show.html.erb
<div class="grid-x grid-padding-x main-grid">
  <div class="cell small-3 main-column">


    <%= render 'folders/entries', folder_service: @folder_service %>
    <%= render 'folders/folder_form', parent_folder: @folder_service.folder %>
    <%= render 'folders/search', folder: @folder_service.folder %>
  </div>
  <% if @folder_service.folder_path? %>
    <%= render 'folders/note_form', parent_folder: @folder_service.folder %>
  <% else %>
    <%= render 'folders/note', note: @folder_service.note %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Notes App" %></title>
    <script
      src="https://code.jquery.com/jquery-3.4.1.js"
      integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
      crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/header/menu' %>

    <div id="main" class="margin-top-30">
      <%= yield %>
    </div>
  </body>
</html>

app/views/search/index.html.erb
<%= form_tag search_index_path, method: "get"  do |f| %>
  <div class="grid-container">
    <div class="grid-x grid-padding-x">
      <div class="medium-12 cell">
        <%= label_tag :id %>
        <%= text_area_tag :id  %>

        <%= label_tag :name %>
        <%= text_area_tag :name %>

        <%= submit_tag :search, class: 'button' %>
      </div>
    </div>
  </div>
<% end %>

<ul class="list-group">
  <% @notes.each do |note| %>
    <li class="list-group-item">
      <i class="fa fa-sticky-note"></i>
      <%= link_to note.permalink, note.permalink %>
    </li>
  <% end %>
</ul>

app/views/shared/header/_menu.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><%= link_to 'Notes App', root_path %></li>
    </ul>
  </div>
</div>